baseURL: 'https://skyknocker.github.io/'
languageCode: en-us
build:
  writeStats: true
title: aafu theme
# Uncomment below to use aafu as hugo theme. See instructions in README.md
theme: "aafu"

params:
  author: Christopher Stevens
  description: Cybersecurity & IT Portfolio
  copyright: powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
      expand: true # only the first `expand: true` will take effect
    - item: experiences
    - item: education
    - item: projects
    - item: skills
      panel_id: skill-panel
    - item: hobbies
  keywords: "Cybersecurity, IT Portfolio, Veteran, Full Sail University, Network Security, Penetration Testing"
markup:
  goldmark:
    renderer:
      unsafe: true